# Generated by Django 3.0.5 on 2021-09-19 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                ("key", models.TextField(primary_key=True, serialize=False)),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "APIkeys",
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("title", models.CharField(max_length=1000)),
                ("description", models.TextField()),
                ("publishedTime", models.DateTimeField()),
                (
                    "videoId",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("channelId", models.CharField(max_length=100)),
                ("createdOn", models.DateTimeField(auto_now_add=True)),
                ("updatedOn", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "Videos",
            },
        ),
        migrations.CreateModel(
            name="VideoThumbNail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screenType", models.CharField(max_length=20)),
                ("url", models.URLField(max_length=1000)),
                ("height", models.IntegerField(null=True)),
                ("width", models.IntegerField(null=True)),
                ("createdOn", models.DateTimeField(auto_now_add=True)),
                ("updatedOn", models.DateTimeField(auto_now=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnail",
                        to="videos.Video",
                    ),
                ),
            ],
            options={
                "db_table": "VideoThumbNails",
            },
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["publishedTime"], name="Videos_publish_cebe50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(fields=["title"], name="Videos_title_633115_idx"),
        ),
    ]
